org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=exturaddon
mod.name=Exturaddon
mod.group=soup587
mod.version = 26.07.26
mod.authors=soup587(Exturaddon), superpowers04(Exturaddon maintainer/Extura), ConstantDust(Extura)
mod.license=PolyForm Noncommercial License 1.0.0
mod.description=Extura but as an addon- AGAIN
mod.sources_url=https://github.com/superpowers04/exturaddon
mod.homepage_url=https://github.com/superpowers04/exturaddon
mod.issues_url=https://github.com/superpowers04/exturaddon/issues

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]

deps.figura=0.1.5
deps.luaj = 3.0.8
deps.nv_websocket = 2.14
