org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=exturaddon
mod.name=Exturaddon
mod.group=soup587
mod.version=0.1.2
mod.authors=ConstantDust, superpowers04, soup587
mod.license=PolyForm Noncommercial License 1.0.0
mod.description=Extura but as an addon again
mod.sources_url=https://github.com/superpowers04/exturaddon
mod.homepage_url=https://github.com/superpowers04/exturaddon
mod.issues_url=https://github.com/superpowers04/exturaddon/issues

deps.minecraft=[VERSIONED]
deps.neoforge=[VERSIONED]

deps.figura=0.1.5
deps.luaj = 3.0.8
deps.nv_websocket = 2.14
