modLoader = "javafml"
loaderVersion = "[47,)"
license = "${license}"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
displayURL = "${homepage_url}"
modUrl = "${homepage_url}"
logoFile = "assets/icon.png"
authors = "${authors}"
logoBlur = false
credits = "${contributors}"
side="CLIENT"

description = '''${description}'''

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft},)"
ordering="NONE"
side="BOTH"
