modLoader = "javafml"
loaderVersion = "[2,)"
license = "${license}"
issueTrackerURL = "${issues_url}"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
displayURL = "${homepage_url}"
modUrl = "${homepage_url}"
logoFile = "assets/icon.png"
authors = "${authors}"
logoBlur = false
credits = "${contributors}"
side="CLIENT"

description = '''${description}'''


[[dependencies."${id}"]]
type="discouraged"
modId="extura"
reason="Exturaddon REPLACES Extura"

[[dependencies."${id}"]]
modId="figura"
type="optional"
reason="Exturaddon is FOR Figura"
ordering="AFTER"
side="CLIENT"

[[mixins]]
config = "${id}.mixins.json"
side="CLIENT"
${dependencies}
